--------------------------------------------------------
--  File created - Monday-February-15-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body TEST_XXPKS_XXDSWYG_CUSTOM
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "FCJLIVE"."TEST_XXPKS_XXDSWYG_CUSTOM" IS

   /* generated by utPLSQL for SQL Developer on 2021-01-15 15:47:27 */

    PROCEDURE fn_pre_check_mandatory IS

        p_source             VARCHAR2(50) := 'Flexcube';
        p_source_operation   VARCHAR2(50) := 'Test';
        p_function_id        VARCHAR2(50) := 'XXDSWYG';
        p_action_code        VARCHAR2(50) := 'NEW';
        p_child_function     VARCHAR2(50) := 'XXSSWYG';
        p_xxdswyg            xxpks_xxdswyg_main.ty_xxdswyg;
        p_err_code           VARCHAR2(50);
        p_err_params         VARCHAR2(50);
        P_RESULT             BOOLEAN;
    BEGIN

    p_xxdswyg.Desc_Fields('A')(1)('A') := 'werewrewrewrewrewr';
    p_xxdswyg.Addl_Info('A') := 'adasdsadkadjajdajdjadjajda';
    p_xxdswyg.v_xxtm_gp_counter_details.cntr_acc_no := '43543543543';
    p_xxdswyg.v_xxtm_gp_counter_details.merchant_id := '00000002323232';

    P_RESULT := xxpks_xxdswyg_custom.fn_pre_check_mandatory(p_source, p_source_operation, p_function_id, p_action_code, p_child_function, p_xxdswyg, p_err_code, p_err_params);

      IF NOT P_RESULT THEN
        ut.expect(p_err_code).to_equal('XX-WYG-01');
        END IF;
    END fn_pre_check_mandatory;

END test_xxpks_xxdswyg_custom;

/
